name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Hardcode package name to com.mobile.legends
        run: |
          chmod +x ./gradlew
          sed -i "s|const char* GamePackageName = .*;|const char* GamePackageName = \"com.mobile.legends\";|g" module/src/main/cpp/game.h

      - name: Build Magisk module
        run: ./gradlew :module:assembleRelease

      - name: Upload zygisk-il2cppdumper
        uses: actions/upload-artifact@v3
        with:
          name: zygisk-il2cppdumper
          path: module/build/outputs/zip/release/module.zip
